name: gl
channels:
  - https://conda.anaconda.org/gurobi
  - defaults
  - conda-forge
  - torch
dependencies:
  - python=3.10
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda
  - pyg::pyg
  - matplotlib
  - plotly
  - ipykernel
  - networkx
  - pygraphviz
  - ipywidgets
  - wandb
